<a href="https://colab.research.google.com/github/Nickguild1993/PyLearn_DS/blob/main/Ch4_LinAlg_Numpy_Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Part Three of going over Numpy for Data Science

Working with Matrices +

In [2]:
# import dependencies 

import pandas as pd
import numpy as np
import random

# visualizations
import matplotlib.pyplot as plt

In [3]:
# Arrays

A = np.random.randint(10, 50, 5)
print(A)
print("-----------------------")
B = [value *2 for value in A if value %2==0]
B = np.array(B)
print(B)

[43 44 47 14 37]
-----------------------
[88 28]


### Matrix Operations 

In [4]:
# Matrices

C = np.array([[1,2,4,6,9], [10,20,40,60,90], [100,200,400,600,900], [1000,2000,4000,6000,9000]])
print(C)
print("-----------------------------------------")
D = [value *2 for value in C]
D = np.array(D)
print(D)
print("-----------------------------------------")
E = [value *3 for value in C]
E = np.array(E)
print(E)

[[   1    2    4    6    9]
 [  10   20   40   60   90]
 [ 100  200  400  600  900]
 [1000 2000 4000 6000 9000]]
-----------------------------------------
[[    2     4     8    12    18]
 [   20    40    80   120   180]
 [  200   400   800  1200  1800]
 [ 2000  4000  8000 12000 18000]]
-----------------------------------------
[[    3     6    12    18    27]
 [   30    60   120   180   270]
 [  300   600  1200  1800  2700]
 [ 3000  6000 12000 18000 27000]]


Adding / Subtractin matrices

In [5]:
T = C + D
print(T)
print("------------------------------------")
# can also use the np.add() function
T = np.add(C,D)
print(T)

[[    3     6    12    18    27]
 [   30    60   120   180   270]
 [  300   600  1200  1800  2700]
 [ 3000  6000 12000 18000 27000]]
------------------------------------
[[    3     6    12    18    27]
 [   30    60   120   180   270]
 [  300   600  1200  1800  2700]
 [ 3000  6000 12000 18000 27000]]


In [6]:
# same as above but using different dtype (floats)
T = np.add(C,D, dtype=float)
print(T)

[[3.0e+00 6.0e+00 1.2e+01 1.8e+01 2.7e+01]
 [3.0e+01 6.0e+01 1.2e+02 1.8e+02 2.7e+02]
 [3.0e+02 6.0e+02 1.2e+03 1.8e+03 2.7e+03]
 [3.0e+03 6.0e+03 1.2e+04 1.8e+04 2.7e+04]]


Subtraction

In [7]:
Z = C- D
print(Z)
print("---------------------------------")
Z = np.subtract(C,D)
print(Z)
print("----------------------------------")
Z = [value *-1 for value in Z]
Z = np.array(Z)
print(Z)

[[   -1    -2    -4    -6    -9]
 [  -10   -20   -40   -60   -90]
 [ -100  -200  -400  -600  -900]
 [-1000 -2000 -4000 -6000 -9000]]
---------------------------------
[[   -1    -2    -4    -6    -9]
 [  -10   -20   -40   -60   -90]
 [ -100  -200  -400  -600  -900]
 [-1000 -2000 -4000 -6000 -9000]]
----------------------------------
[[   1    2    4    6    9]
 [  10   20   40   60   90]
 [ 100  200  400  600  900]
 [1000 2000 4000 6000 9000]]


### Matrix multiplication (Point Wise Multiplication)


In [8]:
print(C)
print("---------------")
print(D)
print("---------------------")
print("Point-wise multplication")
print("--------------------")
A = C * D
print(A)

[[   1    2    4    6    9]
 [  10   20   40   60   90]
 [ 100  200  400  600  900]
 [1000 2000 4000 6000 9000]]
---------------
[[    2     4     8    12    18]
 [   20    40    80   120   180]
 [  200   400   800  1200  1800]
 [ 2000  4000  8000 12000 18000]]
---------------------
Point-wise multplication
--------------------
[[        2         8        32        72       162]
 [      200       800      3200      7200     16200]
 [    20000     80000    320000    720000   1620000]
 [  2000000   8000000  32000000  72000000 162000000]]


### Matrix Division (pointwise)

In [9]:
A = C / D
print(A)
print("--------------------")
A = np.divide(C,D)
print(A)

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]
--------------------
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]


### Matrix Products (Matrix Multiplication. np.matmul()

In [16]:
A = np.array([[4,6,8,10],
              [3,6,9,12]])
B = [value *2 for value in A]
B = np.array(B)
print(A)
print("-----------------------")
print(B)

[[ 4  6  8 10]
 [ 3  6  9 12]]
-----------------------
[[ 8 12 16 20]
 [ 6 12 18 24]]


In [20]:
A

array([[ 4,  6,  8, 10],
       [ 3,  6,  9, 12]])

In [22]:
# np.matmul - > matrix multiplication

np.matmul(B.transpose(), A)

array([[ 50,  84, 118, 152],
       [ 84, 144, 204, 264],
       [118, 204, 290, 376],
       [152, 264, 376, 488]])

Vectors

In [33]:
a = A[:,0]
print(a)
print("------------------------")
b = B[:,0]
print(b)

[4 3]
------------------------
[8 6]


In [34]:
np.dot(a.transpose(),b)


50

### inner product of two arrays

In [35]:
np.inner(a,b)

50